version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build-and-deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: 'Install dependencies'
          command: 'yarn'
      - run:
          name: 'Build application'
          command: 'yarn build'
      - run:
          name: 'Upload files'
          command: 'scp -oStrictHostKeyChecking=no -r ./dist/* $USER@$IP:/$TARGET_PATH'
      - run:
          name: 'Restart server'
          command: 'ssh -oStrictHostKeyChecking=no -v $USER@$IP "$DEPLOY_SCRIPT"'

workflows:
  build-and-deploy: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-deploy
          filters:
            branches:
              only:
                - master